# Generated by Django 4.1.2 on 2022-10-22 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_Biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bibliotecas',
            name='Imagen',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='revistas',
            name='Imagen',
            field=models.URLField(),
        ),
    ]
